[pytest]
markers =
    Smoke:Run the Smoke tests
    Sanity:Run the sanity tests
    demo:Run the demo tests
    Compat:Run the compatability tests(e.g. used in Mobile test)
    owner:Maintainer of the testcase

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

asyncio_mode = auto
asyncio_default_fixture_loop_scope = function

pythonpath = .