[Caps]
platformName = Android
unicodeKeyboard = True
;resetKeyboard = True
automationName = UiAutomator2

[Caps_appium]
platformVersion = 10.0
deviceName = 239588a623057ece
appPackage = com.chinascope.clue
appActivity = io.dcloud.PandoraEntry
noReset = false
;newCommandTimeout = 6000
;ensureWebviewsHavePages = True
nativeWebScreenshot = True
autoGrantPermissions = True

[WebDriver]
;appium 1.x
;command_executor = http://localhost:4723/wd/hub
;appium 2.x
command_executor = http://localhost:4723

[AUT]
test_type = mobile
;need_login = False

[FilePath]
user_file = proj_spec/CLUE/users-uat.csv
header_file = data/headers - Bank_clue_app.json

[URLs]
url1=https://clue-svc-uat.chinascope.com

[Email]
email_host = smtp.qiye.163.com
send_user = message@chinascope.com
password = Q3NmQDIzODg=
user_list = olivia.dou@chinascope.com
cc_list = olivia.dou@chinascope.com

[DB]
db_type = MYSQL
host = mysql-office-proxy.aws-jdaimysql.chinascope.net
port = 5043
username = dept_tech_read_user
password =
database =

[Globals]
implicit_wait = 10
;是否跳过登录步骤(真机上测试时可先登录一次，后续设置为无需登录，同时设置noReset为True，节省调试时间)
skip_login = False

[Framework]
log_level = DEBUG
run_case_folder =
run_case_type = Code



