[URLs]
;web url
url1=

[FilePath]

tc_rootdir = case/triplog/
user_file = %(tc_rootdir)s/users-qa6.csv
;user_file = %(tc_rootdir)s/users-uat.csv
;data_rootdir = data
;header_file = data/headers - DEMO.json
download_path = %(tc_rootdir)s


[Caps]
platformName = ios
;unicodeKeyboard = True
;resetKeyboard = True
automationName = XCUITest

[Caps_appium]
platformVersion = 16.7
deviceName = olivia iPhone 8
udid = 4f3383684005d134dafe0309319c1d2edb2780b6
bundleId = com.bizlogapp.iTripLog
noReset = False
fullReset = False
showXcodeLog = True
newCommandTimeout = 3600
nativeWebScreenshot = True
autoGrantPermissions = True
xcodeOrgId = MM99U5KK27
xcodeSigningId = iPhone Developer
;useNewWDA = True
usePrebuiltWDA = True
shouldTerminateApp = True
;ensureWebviewsHavePages = True,
;nativeWebScreenshot = True,
;connectHardwareKeyboard = True


;[Options]

[WebDriver]
;appium 1.x
;command_executor = http://localhost:4723/wd/hub
;appium 2.x
command_executor = http://localhost:4723

[AUT]
verify = False
test_type = web



[DB]
db_type = MySQL
host = triplogmileage-2023-09-06.chprothzf51j.us-east-2.rds.amazonaws.com
port = 3306
username = bizweb2
;base64encoded password
password = eHVkdm9iLW5pZFpvai01Y2VjYmk=
database = bizweb


[Email]
email_host = smtp.mailserver.com
email_port = 25
;send user's email
send_user = 
password = 
;comma separated list of emails
user_list = 
cc_list = 


[Globals]
;global value that can be used in project functions
key = value


[Framework]
log_level = DEBUG
run_case_level = Smoke,Sanity,Regression
