[URLs]
url1=https://automationexercise.com/


[AUT]
; verify and cert are used for api test in requests.
verify = False
; path of certification file. When proxy is not used, it can be empty even verify is set True.
cert =
; api/mobile/web
test_type = api


[FilePath]
project_rootdir = projects/automation_exercise
; folder of excel test case of api test
tc_rootdir = %(project_rootdir)s/api/case
testcase_file = %(tc_rootdir)s/testcase-automation_exercise.xlsx
data_rootdir = %(project_rootdir)s/data
header_file = headers.json
data_file =



; global values to be used in test
[Globals]


[Framework]
log_level = DEBUG
run_case_level = Smoke,Sanity,Regression
; Type of api test case to run:
;   Excel: Excel-driver general api test case
;   Code: Python Code written for each test case
run_case_type = Excel
;whether to run speicific Excel cases: true/false
run_specific_case = false
; run Code cases under specified folders(separate by comma)
run_case_folder =
retry_wait_time = 5
retry_times = 0





