[URLs]
url1=https://automationexercise.com/


[AUT]
verify = True
cert =
test_type = api


[FilePath]
project_rootdir = projects/automation_exercise
tc_rootdir = %(project_rootdir)s/api/case
testcase_file = %(tc_rootdir)s/testcase-automation_exercise.xlsx
data_rootdir =
header_file =
data_file =


[DB]
db_type =
host =
port =
username =
;base64encoded password
password =
database =



[Email]
email_host =
email_port =
send_user =
password =
;comma separated list of emails
user_list =
cc_list =


[Globals]


[Framework]
log_level = DEBUG
run_case_level = Smoke,Sanity,Regression
; type of api test case to run:
; Excel: Excel-driver general api test case
; Code: Python Code written for each test case
run_case_type = Excel
;whether to run speicific Excel cases: true/false
run_specific_case = false
; run Code cases under specified folders(separate by comma)
run_case_folder =
retry_wait_time = 5
retry_times = 0





