[URLs]
;
url1=https://qa6.triplogmileage.com/web

[Caps]
platformName = Android
;unicodeKeyboard = True
;resetKeyboard = True
automationName = UiAutomator2

[Caps_appium]
platformVersion = 13.0
deviceName = 5e5984e21223
appPackage = com.bizlog.triplog
appActivity = com.esocialllc.triplog.module.setup2.SetupActivity2
;waitActivity = com.esocialllc.triplog.module.setup2.LoginActivity2
; noReset must be set to False, otherwise triplog app won't start
noReset = False
newCommandTimeout = 3600
;ensureWebviewsHavePages = True
nativeWebScreenshot = True
autoGrantPermissions = True
;ensureWebviewsHavePages = True,
;nativeWebScreenshot = True,
;connectHardwareKeyboard = True


;[Options]

[WebDriver]
;appium 1.x
;command_executor = http://localhost:4723/wd/hub
;appium 2.x
command_executor = http://localhost:4723

[AUT]
verify = False
test_type = web

[FilePath]

tc_rootdir = case/triplog/
user_file = %(tc_rootdir)s/users-qa6.csv
;testcase_file = %(tc_rootdir)s/testcase - DEMO.xlsx
;data_rootdir = data
;header_file = data/headers - DEMO.json
download_path = tc_rootdir


[DB]
db_type = MySQL
host = triplogmileage-2023-09-06.chprothzf51j.us-east-2.rds.amazonaws.com
port = 3306
username = bizweb2
;base64encoded password
password = eHVkdm9iLW5pZFpvai01Y2VjYmk=
database = bizweb


[Email]
email_host = smtp.mailserver.com
email_port = 25
;send user's email
send_user = 
password = 
;comma separated list of emails
user_list = 
cc_list = 


[Globals]
;global value that can be used in project functions
key = value


[Framework]
log_level = DEBUG
run_case_level = Smoke,Sanity,Regression
